title: RE Reports
description: Technical analysis, threat intelligence reports, and malware reverse engineering write-ups.
permalink: /:title/

author: Manohar Gonohal
github_username: ManuMW

collections:
  reports:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: reports
    values:
      layout: post

plugins:
  - jekyll-feed
